services:
  db:
    image: postgres
    container_name: TMPTaskServiceDb
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: TMPTaskServiceDb
    ports:
      - "5432:5432"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: TMPTaskService
    ports:
     - "5000:8080"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=TMPTaskServiceDb;Username=myuser;Password=mypassword"
